# Use the official Nginx image as the base image
FROM nginx:alpine

# Copy your frontend code to the appropriate directory in the image
COPY ./dist /usr/share/nginx/html

# Expose the port that the Nginx server will listen on
EXPOSE 80
